# Generated by Django 4.2.5 on 2024-01-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diabetes_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('pregnancy', models.CharField(max_length=30)),
                ('glucose', models.CharField(max_length=30)),
                ('bp', models.CharField(max_length=30)),
                ('insulin', models.CharField(max_length=30)),
                ('bmi', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=30)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
