# Generated by Django 4.2.5 on 2024-01-04 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Diabetes', '0002_rename_bp_diabetes_data_blood_pressure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diabetes_data',
            old_name='age',
            new_name='p_age',
        ),
        migrations.RenameField(
            model_name='diabetes_data',
            old_name='blood_Pressure',
            new_name='p_blood_Pressure',
        ),
        migrations.RenameField(
            model_name='diabetes_data',
            old_name='bmi',
            new_name='p_bmi',
        ),
        migrations.RenameField(
            model_name='diabetes_data',
            old_name='gender',
            new_name='p_gender',
        ),
        migrations.RenameField(
            model_name='diabetes_data',
            old_name='glucose',
            new_name='p_glucose',
        ),
        migrations.RenameField(
            model_name='diabetes_data',
            old_name='insulin',
            new_name='p_insulin',
        ),
        migrations.RenameField(
            model_name='diabetes_data',
            old_name='name',
            new_name='p_name',
        ),
        migrations.RenameField(
            model_name='diabetes_data',
            old_name='pregnancy',
            new_name='p_pregnancy',
        ),
        migrations.RenameField(
            model_name='diabetes_data',
            old_name='time',
            new_name='p_time',
        ),
    ]
