# Generated by Django 4.2.5 on 2024-01-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diabetes', '0004_rename_p_age_diabetes_data_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabetes_data',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='diabetes_data',
            name='blood_Pressure',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='diabetes_data',
            name='bmi',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='diabetes_data',
            name='glucose',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='diabetes_data',
            name='insulin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='diabetes_data',
            name='pregnancy',
            field=models.IntegerField(),
        ),
    ]
