# Generated by Django 4.2.5 on 2024-01-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diabetes', '0005_alter_diabetes_data_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='diabetes_data',
            name='bmi',
            field=models.FloatField(),
        ),
    ]
